### ISSUE TITLE
When requiring module. Receive error.

### ISSUE THREAD

**Issue by Frustrated-Programmer** [bradmartin/nativescript-color-picker#14]
So following the `readme` I installed the module, rebuilt and reinstalled my app.

When I run `let cpModule = require('nativescript-color-picker');`  I get the following error:
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException:
Calling js method onClick failed

Error calling module function

Error calling module function

TypeError: Cannot read property 'ColorMode' of undefined
File: "file:///data/data/org.nativescript.prayerApp/files/app/tns_modules/nativescript-color-picker/colorpicker.js, line: 6, column: 54
```
This chunk of the error i felt was the *relevant* part. . .
but for the anyone who wishes to have it, I have the **full** error here: https://pastebin.com/tz8wEXLy

Can anyone instruct me on how to fix/correct this?

**Comment by bradmartin** [comment]
Assuming you're on android, due to the error `ColorMode` which is part of the native library that the plugin installs.

Did you remove your platform and add it back after adding the plugin? There is also a `clean` command in the TNS CLI that will do both steps if you like the brevity :) this def. seems like a build issue that the lib isn't actually in the executable (apk) you're running. Try removing/adding the platform.

I wrote about this long time ago here https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/ - simple to overlook this and a PITA when it happens 😄

**Comment by Frustrated-Programmer** [comment]
Thank you! yea I did rebuild & remove the app before,
though I was unaware of `clean` command. 
And after I used it, I got it working 👍
