### ISSUE TITLE
How to use it with pure Javascript?

### ISSUE THREAD

**Issue by d3mac123** [bradmartin/nativescript-color-picker#8]
How to code this for Javascript? I am trying:
var ColorPicker = require("nativescript-color-picker")
var picker = new ColorPicker();
       picker.show('#3489db', 'ARGB').then((result) => {
            console.log('color int: ' + result);
        }).catch((err) => {
            console.log(err)
        })

but I am getting this error:
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method onClick failed

TypeError: ColorPicker is not a constructor
File: "file:///data/data/com.asouza.buddyFinder/files/app/settings-view-model.js, line: 74, column: 20

**Comment by bradmartin** [comment]
Hi @d3mac123 -

You are close :) to having it. So with your `require('nativescript-color-picker')` you are just grabbing the module itself. Which is why you get the error `ColorPicker is not a constructor` because basically what you have reads like this: `var ColorPicker is the color-picker module` which makes sense. The .ts source here https://github.com/bradmartin/nativescript-color-picker/blob/master/colorpicker.android.ts#L20 is what you are going to use as your class constructor. So you have two options. You can use:

``` js
/// this reads as var whatever is the ColorPicker class and not just the module
var whatever = require('nativescript-color-picker').ColorPicker;

/// this reads as whatever is the module and then var picker is accessing the ColorPicker class.
var whatever = require('nativescript-color-picker');
var picker = new whatever.ColorPicker();
```

With the TS import of `{ ColorPicker }` it just simplifies the require/import. When transpiled it's just a require statement but simpler to write. Hope that helps.

**Comment by d3mac123** [comment]
Beautiful! Thanks for the solution and explanation!

**Comment by bradmartin** [comment]
If you have any other issues let me know 😄
